# Generated by Django 5.0.3 on 2024-04-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500, verbose_name='category description')),
                ('title', models.CharField(max_length=100, verbose_name='category title')),
                ('amount', models.IntegerField(verbose_name='product amount')),
                ('price', models.FloatField(verbose_name='product price')),
                ('images', models.CharField(verbose_name='product image')),
                ('active', models.BooleanField(verbose_name='active')),
            ],
        ),
    ]
